import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shopping Mall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="nav-bar">
          <Link href='/'><h2>musinsa</h2></Link>
          <LoginBtn/>
          {/* <img className='profile-img' src={
            
          }></img> */}
        </div>
        {children}
      </body>
    </html>
  );
}
